DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

CREATE TABLE COUNTRY (
    countryID SERIAL UNIQUE,
    countryName VARCHAR(255),
    PRIMARY KEY (countryID)
);

CREATE TABLE UNIVERSITY (
    universityID SERIAL UNIQUE,
    countryID INT NOT NULL REFERENCES COUNTRY(countryID)  ON DELETE CASCADE ON UPDATE CASCADE,
	universityName VARCHAR(255),
    PRIMARY KEY (universityID, countryID)
);


CREATE TABLE EVALUATION_SYSTEM (
    evaluationSystemID SERIAL,
    countryID INT NOT NULL REFERENCES COUNTRY(countryID) ON DELETE CASCADE ON UPDATE CASCADE,
	universityID INT NOT NULL REFERENCES UNIVERSITY(universityID) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (evaluationSystemID)
);


CREATE TABLE GRADE_CONVERSION (
    gradeConversionID SERIAL,
    evaluationSystemID INT NOT NULL REFERENCES EVALUATION_SYSTEM(evaluationSystemID) ON DELETE CASCADE ON UPDATE CASCADE,
	gradeMin FLOAT,
	gradeMax FLOAT, 
	base FLOAT,
	factor FLOAT,
	top FLOAT,
    PRIMARY KEY (gradeConversionID)
);